Fix staging
Murmele/Gittyup pull request #122
Opened 2022-03-31 17:30 UTC by Murmele

The first should be selected, but it is the last. Don't know if this can be change.
But when clicking on the first deletion the last gets selected

![image](https://user-images.githubusercontent.com/10099533/161114852-f44f2b65-d6b2-4ee3-9890-43689bfc044b.png)

2022-04-02 11:19 UTC, exactly-one-kas requested changes
Aside from a bit of cleanup that needs to be done and some preprocessor abuse this looks fine

2022-04-02 11:19 UTC, exactly-one-kas commented on src/ui/DiffView/HunkWidget.cpp
> +//	int diff_patch_old_new_file = 0;
Please remove these remnants

2022-04-02 11:19 UTC, exactly-one-kas commented on src/ui/DiffView/HunkWidget.cpp
> +//                    diff_patch_old_new_file = 0; //mPatch.lineNumber(mIndex, lidx, git::Diff::NewFile) - mPatch.lineNumber(mIndex, lidx, git::Diff::OldFile);
Also these

2022-04-02 11:19 UTC, exactly-one-kas commented on src/ui/DiffView/HunkWidget.cpp
> +//				auto staged_file = mStaged.lineNumber(current_staged_index, current_staged_line_idx, git::Diff::NewFile) - diff_staged_patch_old_new_file;
Also these

2022-04-02 11:19 UTC, exactly-one-kas commented on test/EditorLineInfos.cpp
> +#define private public
Maybe replace this with something akin to

```
#define public_for_tests public
```

and inside the headers use
```
#ifndef public_for_tests
    #define public_for_tests private
#endif
```

2022-04-02 11:19 UTC, exactly-one-kas commented on test/EditorLineInfos.cpp
> +	// TODO: release fw
Isn't this TODO done in line 658?

2022-04-02 11:24 UTC, Murmele commented on src/ui/DiffView/HunkWidget.cpp
> +//	int diff_patch_old_new_file = 0;
done

2022-04-02 11:24 UTC, Murmele commented on src/ui/DiffView/HunkWidget.cpp
> +//                    diff_patch_old_new_file = 0; //mPatch.lineNumber(mIndex, lidx, git::Diff::NewFile) - mPatch.lineNumber(mIndex, lidx, git::Diff::OldFile);
done

2022-04-02 11:24 UTC, Murmele commented on src/ui/DiffView/HunkWidget.cpp
> +//				auto staged_file = mStaged.lineNumber(current_staged_index, current_staged_line_idx, git::Diff::NewFile) - diff_staged_patch_old_new_file;
done

2022-04-02 11:25 UTC, Murmele commented on test/EditorLineInfos.cpp
> +	// TODO: release fw
thanks I forgott

2022-04-02 11:26 UTC, Murmele commented
> Aside from a bit of cleanup that needs to be done and some preprocessor abuse this looks fine

Thanks for reviewing. For some reason the windows build failed

2022-04-02 11:36 UTC, exactly-one-kas commented on test/EditorLineInfos.cpp
> +#define private public
~I really don't like these `#define` shenanigans. If you want, I can implement the changes I requested.~

```
EditorLineInfos.cpp.obj : error LNK2001: unresolved external symbol "public: void __cdecl HunkWidget::stageSelected(int,int,bool)" (?stageSelected@HunkWidget@@QEAAXHH_N@Z)
```
Looks like on Windows changing the visibility of methods / slots also affects name mangling and/or whether they get exported or not.
I think we should promote `stageSelected` to `public`

2022-04-02 11:37 UTC, exactly-one-kas commented
> For some reason the windows build failed

Yep, I unresolved the `#define` review comment with additional information

2022-04-02 11:48 UTC, Murmele commented on test/EditorLineInfos.cpp
> +#define private public
I will have a look

2022-04-02 11:50 UTC, Murmele commented on test/EditorLineInfos.cpp
> +#define private public
done

2022-04-02 11:51 UTC, Murmele commented
> > For some reason the windows build failed
> 
> Yep, I unresolved the `#define` review comment with additional information

sorry there I was too fast

2022-04-03 08:44 UTC, exactly-one-kas approved these changes

2022-04-03 12:30 UTC, merged