Donation
Murmele/Gittyup pull request #130
Opened 2022-04-19 11:27 UTC by Murmele

@stefanknotzer @exactly-one-kas would you like to create an account at liberapay so I can add you?

2022-04-19 18:11 UTC, exactly-one-kas requested changes

2022-04-19 18:11 UTC, exactly-one-kas commented on src/dialogs/AboutDialog.cpp
> +const QString kEmail = QStringLiteral("https://github.com/Murmele/Gittyup/issues");
- [ ] Rename this variable to something like `kIssueTracker`

2022-04-19 18:11 UTC, exactly-one-kas commented on rsrc/Liberapay_Icon_Readme.md
> + source: https://icon-icons.com/icon/liberapay/130890
- [ ] I think the attribution also needs to be visible from the compiled App

2022-04-19 18:11 UTC, exactly-one-kas commented on src/ui/MenuBar.cpp
> +  QAction* donation = help->addAction(tr("Support us over Liberapay"));
- [ ] I think this should read "Support us *via* Liberapay"

2022-04-19 18:11 UTC, exactly-one-kas commented on src/update/Updater.cpp
>    [this](const QString &version, const QString &log, const QString &link) {
- [ ] Resolve the TODO in line 47

2022-04-19 18:12 UTC, exactly-one-kas commented
@Murmele Thanks for the offer, but I already have a steady source of income

2022-04-22 08:45 UTC, Murmele commented on rsrc/Liberapay_Icon_Readme.md
> + source: https://icon-icons.com/icon/liberapay/130890
I added the source to the Acknowledments

2022-04-22 08:58 UTC, Murmele commented
@exactly-one-kas I added a messagebox if the platform is linux (and not flatpak) if it should be really downloaded manually. GitAhead had a shell script which extracts it self. I don't like that people are installing it without package manager because it is hard to remove everything at uninstall

2022-04-23 16:24 UTC, Murmele commented
I added to every step the following condition:
`if: ${{ github.ref == 'refs/heads/master' || env.IS_RELEASE}}`
The problem is that for some reason the env is not available in the jobs. Maybe you know something about?

2022-04-26 12:12 UTC, exactly-one-kas commented
> I added a messagebox [...]

Manual installation and updating shouldn't be too much of a problem if it's inside a self-contained directory, especially if you want to use bleeding-edge builds.

Also, wouldn't it be better to simply remove the self-update button for linux binary builds?

> The problem is that for some reason the env is not available in the jobs

The environment variable is available, but it's a string, so it evaluates to `true` (only empty strings are considered falsey).
This should work using `${{ github.ref == 'refs/heads/master' || env.IS_RELEASE != 'false' }}`

2022-04-26 12:21 UTC, Murmele commented
> Also, wouldn't it be better to simply remove the self-update button for linux binary builds?

Yeah maybe thats a good idea. So I remove any update functionality on linux? Maybe I just write down that system should be updated to receive the newest version?

2022-04-26 12:25 UTC, Murmele commented
> 

when I tried to add it only for the job I got the following error message:
`The workflow is not valid. .github/workflows/build.yml (Line: 270, Col: 9): Unrecognized named-value: 'env'. Located at position 1 within expression: env.IS_RELEASE`
https://github.com/Murmele/Gittyup/actions/runs/2212832925

2022-04-26 13:02 UTC, exactly-one-kas commented
Yes, the `if` on the whole job doesn't work with env (since there's no environment without a started VM / container)
You can only use the `if`s on steps.

2022-04-26 16:54 UTC, Murmele commented
Flatpak package:
![image](https://user-images.githubusercontent.com/10099533/165352741-819e0d60-ec2a-4ec6-9b90-04b56dee98f5.png)

2022-04-26 19:07 UTC, Murmele commented
> Yes, the `if` on the whole job doesn't work with env (since there's no environment without a started VM / container) You can only use the `if`s on steps.

I just copied now the IS_RELEASE condition again into the job if, instead having in every step the condition

2022-04-29 10:31 UTC, exactly-one-kas requested changes

2022-04-29 10:31 UTC, exactly-one-kas commented on src/update/UpdateDialog.cpp
> +  connect(this, &UpdateDialog::accepted, [/*this,*/ platform, link] {
Please remove the comment

2022-04-29 10:31 UTC, exactly-one-kas commented on src/update/Updater.cpp
> +  "link<https://github.com/Murmele/gittyup/releases/download/v%1/Gittyup%2-%3.%4>";
This should only have the URL part

2022-04-29 15:46 UTC, Murmele commented on src/update/UpdateDialog.cpp
> +  connect(this, &UpdateDialog::accepted, [/*this,*/ platform, link] {
done

2022-04-30 08:44 UTC, merged