implement keypress otherwise a segfault occurs
Murmele/Gittyup pull request #184
Opened 2022-06-02 13:37 UTC by Murmele

potential fix of #109

Use the procedure in #109 to reproduce the segfault

fix occurs also in 96c2fb50778da0ffcbad95ed59572299508773a8

2022-06-04 14:41 UTC, stefanknotzer commented
My quick-fix:

![Segfault](https://user-images.githubusercontent.com/67198194/172007776-cd3dc970-9608-4ab7-aa1b-ceabdaa6e3a1.png)

2022-06-05 15:01 UTC, Murmele commented
> 

hmm I have to check, because I did not see the problem at this assert. For me it seems to be an assert in the qt lib

2022-06-08 07:41 UTC, Murmele commented
@stefanknotzer can you try with the repository I posted in #109 if you get the segfault at the same position than me. Maybe we have multiple bugs here

2022-06-09 16:00 UTC, stefanknotzer commented
I was able to build 96c2fb50778da0ffcbad95ed59572299508773a8 but I can't reproduce the segfault any more

2022-06-09 16:07 UTC, stefanknotzer approved these changes

2022-06-10 07:37 UTC, Murmele commented
> 

On which operating system?

2022-06-10 15:01 UTC, stefanknotzer commented
Windows 10 and openSUSE LEAP 15.3.
Is the problem caused by a race condition? Then the Qt Version / gcc version / Visual Studio version could make a difference.

2022-06-13 11:43 UTC, Murmele commented
> Windows 10 and openSUSE LEAP 15.3. Is the problem caused by a race condition? Then the Qt Version / gcc version / Visual Studio version could make a difference.

I tested it on Windows 10 with Qt 5.15.2 MinGW 64-bit commit: 96c2fb50778da0ffcbad95ed59572299508773a8

2022-06-19 09:31 UTC, stefanknotzer commented
Windows 10, Qt 5.15.0, MSVC2019 64Bit: no segfault with the test repo from #109

2022-08-12 14:09 UTC, Murmele commented
I tested it on Linux Debug with Qt5.15.5 and it is still reproducable

2022-08-12 14:19 UTC, Murmele commented
@exactly-one-kas from my side we can merge it, because I am still able to reproduce the issue and this solves the issue. Do you have any concers?

2022-08-12 18:12 UTC, exactly-one-kas requested changes
Aside from a small superficial nitpick, this looks fine

2022-08-12 18:12 UTC, exactly-one-kas commented on src/ui/TreeView.cpp
> + * later version if it can be proved that the problem is solved. \param event
Remove `\param event`

2022-08-12 18:59 UTC, Murmele commented on src/ui/TreeView.cpp
> + * later version if it can be proved that the problem is solved. \param event
```suggestion
 * later version if it can be proved that the problem is solved.
```

2022-08-12 20:27 UTC, Murmele commented on src/ui/TreeView.cpp
> + * later version if it can be proved that the problem is solved. \param event
Done

2022-08-14 16:02 UTC, stefanknotzer commented on src/ui/TreeView.cpp
> +  } else
```suggestion
    model()->setData(index, checkState, Qt::CheckStateRole);
    
    // Select next item.
    QKeyEvent *down =
        new QKeyEvent(event->type(), Qt::Key_Down, event->modifiers());
    QTreeView::keyPressEvent(down);
  } else
```

2022-08-22 09:51 UTC, Murmele commented on src/ui/TreeView.cpp
> +  } else
So that would mean if any other key will be pressed we are going to the next item (even if we are pressing up key ) or?
Isn't this an infinit loop if we never have a currentIndex?

2022-08-22 15:13 UTC, stefanknotzer commented on src/ui/TreeView.cpp
> +  } else
No, after the space key is pressed, an additional down key is inserted (and the next line is selected).
On any other key event no additional down key is inserted.

2022-08-23 14:37 UTC, Murmele commented on src/ui/TreeView.cpp
> +  } else
ah sorry yes it is above the else.

2022-08-24 15:14 UTC, stefanknotzer approved these changes

2022-09-07 06:53 UTC, merged