Fix supportlink, remove video section and fix flatpak download url
Murmele/Gittyup pull request #238
Opened 2022-08-12 09:30 UTC by Murmele

- use matrix as support link
- currently we don't have any videos
- remove dot because it is already in the kLinkFmt

2022-08-12 18:11 UTC, exactly-one-kas requested changes

2022-08-12 18:11 UTC, exactly-one-kas commented on src/ui/TabWidget.cpp
> +    // layout->addWidget(addLink(tr("View getting started videos"),
Add a `TODO` comment so that it won't get deleted by accident

2022-08-12 18:57 UTC, Murmele commented on src/ui/TabWidget.cpp
> +    // layout->addWidget(addLink(tr("View getting started videos"),
```suggestion
    // TODO: uncomment as soon as we have videos
    // layout->addWidget(addLink(tr("View getting started videos"),
```

2022-08-12 20:28 UTC, Murmele commented on src/ui/TabWidget.cpp
> +    // layout->addWidget(addLink(tr("View getting started videos"),
Done

2022-08-15 15:09 UTC, exactly-one-kas approved these changes

2022-08-22 09:07 UTC, merged