Fix updater not closing all main windows
Murmele/Gittyup pull request #245
Opened 2022-08-18 05:00 UTC by exactly-one-kas

For some reason, using QCoreApplication::notify() with a QCloseEvent never reaches any MainWindow, so now they get closed explicitly

2022-08-22 09:44 UTC, Murmele requested changes

2022-08-22 09:44 UTC, Murmele commented on src/update/CMakeLists.txt
> +  git
Why do we need git here?

2022-08-22 09:55 UTC, Murmele commented
We have to implement install() for flatpak

2022-08-22 11:15 UTC, Murmele commented
fixes #240

2022-08-22 14:04 UTC, exactly-one-kas commented on src/update/CMakeLists.txt
> +  git
It's a transitive dependency of `MainWindow`, without this it doesn't find the libgit2 headers

2022-08-25 13:11 UTC, Murmele commented
@exactly-one-kas do we need the backport or shall we publish a new version from master?

2022-08-25 14:11 UTC, Murmele commented
Flatpak is not working yet

2022-09-19 05:45 UTC, Murmele commented
@exactly-one-kas Flatpak is working. Can you try again windows? After you can merge

2022-09-19 05:46 UTC, Murmele approved these changes

2022-09-20 07:34 UTC, Murmele commented
@franktopel Can you test with the build artifacts if it is working now on macOs?

2022-09-20 15:32 UTC, Murmele commented
Tested on windows and it works

2022-09-20 15:34 UTC, franktopel commented
> @franktopel Can you test with the build artifacts if it is working now on macOs?
> https://github.com/Murmele/Gittyup/actions/runs/3080094215

I'm willing to help, but I need detailed information as of what exactly to do.

2022-09-20 15:36 UTC, Murmele commented
> 

Just install the dmg file. Verify the version (Help->About Gittyup) is 1.1.1. Check for updates and install the update.
After updating check again the version. It should be 1.1.2. Thank you!

2022-09-20 15:56 UTC, franktopel commented
After installing, upon first running Gittyup it immediately starts downloading Gittyup 1.1.2 (which is highly irritating, did it even ask me?). I've cancelled the process and then asked for the current version ("About Gitty"):

<img width="740" alt="image" src="https://user-images.githubusercontent.com/10668603/191305186-99cc5fed-d3e2-44ca-84a0-9e0d07dfdfd2.png">

Then if I manually "Check for Updates" it again won't just tell me there is a new version and ask me to download it, but rather start the download unasked again. Since I have quite a fast connection I was only able to screenshot what shows up after the download is finished:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/10668603/191305799-9fc899d9-7b48-4978-8423-3b95ceab4ba8.png">

After clicking "Install and restart" I get the next annoying thing (why didn't any other Git-GUI result in me being asked this? Sublime Merge, Sourcetree, Github Desktop, Tower, git-gui):

<img width="409" alt="image" src="https://user-images.githubusercontent.com/10668603/191305998-e34fb674-75c8-4f09-b974-03d86d4837b2.png">

After permitting incoming connections, Gittyup starts and shows this when asking "About Gitty":

<img width="740" alt="image" src="https://user-images.githubusercontent.com/10668603/191306527-a0377eb9-42a0-49a5-ae21-e6517475acea.png">

2022-09-20 16:09 UTC, Murmele commented
> ermitting incoming connections, Gittyup starts and shows this when asking "About Gitty":

Perfect thanks!

2022-09-20 16:09 UTC, Murmele commented
@exactly-one-kas If you agree you can merge

Tested:
- flatpak
- Windows x64
- macOS

2022-09-20 19:16 UTC, exactly-one-kas commented
The "incoming connections" problem should be fixed with 1.1.3

I just pushed another committ that disables auto updates when the user didn't choose to automatically install
This will only fix versions 1.1.3 and up though

2022-09-20 19:17 UTC, exactly-one-kas commented
@franktopel The "incoming connections" dialog is because of our GitHub host implementation - it starts an unused HTTP server that presumably was implemented in order to use OAuth

2022-09-20 19:17 UTC, exactly-one-kas commented
@Murmele I'll check this with Windows tomorrow

2022-09-20 20:42 UTC, Murmele commented
> @Murmele I'll check this with Windows tomorrow

Don't stress you haha thanks :) . Thanks fo :)r merging the others

2022-09-23 11:04 UTC, merged