Adds quick commit author overriding
Murmele/Gittyup pull request #26
Opened 2021-11-23 10:59 UTC by exactly-one-kas

2021-12-12 16:16 UTC, Murmele requested changes

2021-12-12 16:16 UTC, Murmele commented on src/ui/DetailView.cpp
> +    QDialog *dialog = new QDialog(this);
Adding a title?
Or a description what happens when the user changes something in this dialog?

2021-12-12 16:16 UTC, Murmele commented on src/ui/DetailView.cpp
> +      mOverrideEmail = emailEdit->text();
Should we store the data in the config, so it is stored for that project and will not be reset every time?

2021-12-12 20:34 UTC, exactly-one-kas commented on src/ui/DetailView.cpp
> +      mOverrideEmail = emailEdit->text();
Email and author are already saved per repository. This only adds ad-hoc overriding

2021-12-14 09:46 UTC, Murmele commented on src/ui/DetailView.cpp
> +      mOverrideEmail = emailEdit->text();
ok

2021-12-14 09:47 UTC, Murmele commented on src/ui/DetailView.cpp
> +    QDialog *dialog = new QDialog(this);
@exactly-one-kas Please write done or something that I know you changed this. Thanks :)

2021-12-14 09:52 UTC, merged