Fix reference view
Murmele/Gittyup pull request #271
Opened 2022-09-07 13:05 UTC by Murmele

## First Problem solved by first commit
1) Select commit which does not have a lokal branch, but only a remote branch
2) Try to rebase
--> Rebase button is disabled, because ref is not valid.
Solution: It must be also done like for the branch adding 1 because the first is an invalid ref.

## Second Problem solved by second commit
1) Select commit which does not have any branches/remotes/tags ...
2) try to rebase
--> Rebase button is disabled, because ref is invalid.
Solution: return the current selected commit if available

2022-09-07 15:22 UTC, exactly-one-kas requested changes

2022-09-07 15:22 UTC, exactly-one-kas commented on src/ui/ReferenceView.cpp
> +          return createIndex(0 + 1, 0, ReferenceType::Remotes);
Replace `0 + 1` with `1`

2022-09-13 11:16 UTC, Murmele commented on src/ui/ReferenceView.cpp
> +          return createIndex(0 + 1, 0, ReferenceType::Remotes);
changed in 6db9b72dac98f425f5667981f2959d9a581e8e3f

2022-09-20 19:28 UTC, exactly-one-kas approved these changes

2022-09-20 19:28 UTC, merged