Implement Amend Dialog
Murmele/Gittyup pull request #273
Opened 2022-09-19 09:34 UTC by Murmele

Currently amend is implemented as soft reset. This might lead to undesired changes lost if someone did not realized that it did a reset.

Implement a dialog and change data there and then amend with the libgit2 functionality.

2022-09-19 17:20 UTC, Murmele commented
![image](https://user-images.githubusercontent.com/10099533/191076033-eac1be5d-ae3b-4a12-a9f3-c0e476a9771d.png)

![image](https://user-images.githubusercontent.com/10099533/191076113-4ee4b93d-8117-4941-9fb3-ac63f10fcde4.png)

2022-09-19 17:22 UTC, Murmele commented
@Minabsapi @lonix1 is this what you would like to have?

TODO: currently the date will be used from the old commit. Should it be changed too?

2022-09-19 18:01 UTC, Murmele commented
@exactly-one-kas what do you think?

2022-09-19 19:31 UTC, Minabsapi commented
> @Minabsapi @ lonix1 is this what you would like to have?

A supplementary field to edit author date would also be nice, but this aside, this is what I'd like

2022-09-20 12:02 UTC, Murmele commented
> 

I think this is not the same thing as amend. Then you have to do a rebase soft or?

2022-09-20 12:03 UTC, Murmele commented
> 

I think this is not the same thing as amend. Then you have to do a rebase soft or? At least from the libgit2 function it seems to be not possible doing something like this.

2022-09-20 12:40 UTC, Murmele commented
> That is unfortunate, but I understand you about the complexity.
> 
> But, if that's the case, please rename it from amend? git amend and git soft reset are two different things, and it will be very confusing to people to do it and find it does something else...that's what happened to me and so I opened the original issue.

Why renaming it? It is amend withouth the possibility to add new files. (The new implementation using libgit2 git_commit_ammend())

2022-09-20 16:04 UTC, Murmele commented
> 

I am curious what is for you the difference between soft reset + committing again and amend?

For me amend gives the possibility to change the properties of a commit.
- name, email for author committer (now possible)
- date of the original commit, date of the committer commit (not implemented in Gittyup)
- as I know now thanks to you it is possible to add new files (not possible in Gittyup)
```
# Edit hello.py and main.py
git add hello.py
git commit 
# Realize you forgot to add the changes from main.py 
git add main.py 
git commit --amend --no-edit
```
https://www.atlassian.com/git/tutorials/rewriting-history

A soft reset is a reset to the previous commit staging all the files again which have been in the commit. If I change the commit message and commit again then it is the same as I am doing an amend and changing only the commit message.

So one thing you can achive with amend what is not possible with a soft reset is that you add a file without changing the author name and email (Because when committing again, commiter and author got set to the current user).

The problem implementing amend with changing files is that we have to change the treeview (or adding it to the dialog) which makes it really complicated.

I think with this MR we have a correctly implemented amend command, with a limited set of capabilities (only name and and email can be changed).
Of course it is a big benefit, because now the amend command does not anything unexpected. And if you would like to edit a commit more than just editing credentials you just do a soft reset and committing afterwards.

2022-09-20 18:55 UTC, exactly-one-kas commented
`amend` basically does the same as a soft reset + committing, albeit in one stroke (and therefore only writing one entry in the reflog)
`git_commit_amend` has the optional parameter `tree`
Using `git_index_write_tree` here to create a tree from the current index should achieve the desired effect of adding all staged changes to the amended commit

This has the same behavior as the CLI (and allows our users to have `amend` mean the same thing across all GIT frontends) and also allows changes to amend to be added externally

2022-09-20 18:59 UTC, exactly-one-kas requested changes
LGTM, but I'd also prefer to have staged changes added to the amended commit (see https://github.com/Murmele/Gittyup/issues/273#issuecomment-1252779508)

2022-09-20 18:59 UTC, exactly-one-kas commented on src/ui/RepoView.cpp
> +  // TODO: maybe also editing date...
Remove this - I created an issue for this: #277

2022-09-20 20:41 UTC, Murmele commented
@exactly-one-kas thanks for the clarification. How would you like to implement it? Not sure how to do this graphically?

2022-09-21 06:10 UTC, Murmele commented
> ```
> ...OOPS! I forgot some things
> git add blah.c
> git add qux.js
> git commit --amend   # uses same message
> # oops! I'm a dummy... fix blah.c again!
> git add blah.c
> git commit --amend   # uses same message
> ```
> 
> 
>     
>   
> 
> In most GUI tools all that can be done like this:
> 
> 
>     * stage files
> 
> 
>     * amend
> 
> 
> 
> 
> Incredibly easy and useful.

Ah that makes sense implementing like this. So you stage before and then you are doing the amend. I think this can be implemented. Sorry for my missunderstanding.

2022-09-21 06:11 UTC, Murmele commented on src/ui/RepoView.cpp
> +  // TODO: maybe also editing date...
```suggestion
```

2022-09-21 23:30 UTC, Murmele commented
> No, _I'm sorry_ for harassing you. 😄 I got a little excited because Gittyup has such a promising future. There are no modern cross platform gitkraken/sourcetree-like apps anymore, which are actively maintained. Except for Gittyup. It's really awesome. Thanks for maintaining it!

Yes this is true 😄 this was also the reason why I forked GitAhead a few years ago 😄 especially on linux there are not that many guis. GitKraken is just slow . Gittyup is not perfect there but way better 😄 Thanks to all the contributors especially to @exactly-one-kas i think we setup up a really good infrastructure to easly manage the project and pushing it forward 🚀

2022-09-21 23:38 UTC, Murmele commented
https://github.com/libgit2/libgit2/blob/ac0f2245510f6c75db1b1e7af7ca01c15dec26bc/tests/libgit2/object/commit/commitstagedfile.c

Then lets implementing amending the staged files

2022-09-22 12:44 UTC, Murmele commented
> https://github.com/libgit2/libgit2/blob/ac0f2245510f6c75db1b1e7af7ca01c15dec26bc/tests/libgit2/object/commit/commitstagedfile.c
> 
> Then lets implementing amending the staged files

Ok it was easier than expected to implement amending files

2022-09-22 18:52 UTC, exactly-one-kas approved these changes

2022-09-23 14:14 UTC, exactly-one-kas commented
@Murmele I fixed a thing, can you look over it?

2022-09-24 05:47 UTC, Murmele commented
Oh I did not realize that there is already an amendCommit Test haha ^^

Will this be still correctly?
![image](https://user-images.githubusercontent.com/10099533/192081931-ba154168-0ddd-4901-a8d0-ad8c33225bd1.png)
![image](https://user-images.githubusercontent.com/10099533/192082117-0a10a934-e61e-4592-8d09-c1e8298cd543.png)

Maybe we can change the message somehow that the parent commit is not needed?

2022-09-24 06:15 UTC, exactly-one-kas commented
> Will this be still correctly?

How about just moving the message to after `mRepo.amend()` and  using `head.target().link()`?

2022-09-24 10:45 UTC, Murmele commented
> 

Yes we can try

2022-09-25 09:37 UTC, Murmele commented
> 

I tried it, but it seems to be not correct

2022-09-25 09:47 UTC, Murmele commented
@exactly-one-kas I pushed another proposal

2022-09-25 10:04 UTC, exactly-one-kas commented
Using the parent would simply be wrong, since the branch isn't pointing to the parent - it's pointing to the newly amended commit

2022-09-25 10:43 UTC, exactly-one-kas commented
@Murmele does my proposal work?

2022-09-25 11:48 UTC, Murmele commented
> > Will this be still correctly?
> 
> How about just moving the message to after `mRepo.amend()` and using `head.target().link()`?

I that case is is pointing to the commit id previously was used by the commit which will be amended

2022-09-25 11:52 UTC, Murmele commented
This is how it looks now with by proposal:
Startpoint
![image](https://user-images.githubusercontent.com/10099533/192141969-2486cb3a-23fd-405e-84c3-edf0ca496bf9.png)

After amend
![image](https://user-images.githubusercontent.com/10099533/192142007-c343da5b-4a69-40ac-8687-b6de38f168d7.png)

2022-09-25 11:58 UTC, Murmele commented
> @Murmele does my proposal work?

@exactly-one-kas  hmm sorry I did something wrong when I tested first time and then it showed me again the old id. using the new commit id is great.

2022-10-04 09:50 UTC, exactly-one-kas commented
I'd say yes

2022-10-10 16:24 UTC, Murmele commented
From my side this is ready

2022-10-10 16:33 UTC, merged

2022-11-03 07:57 UTC, Murmele commented
@lonix1 thanks for the compliment. Great to hear that it simplifys your workflow