Add support for running in single instance mode on Linux and Windows
Murmele/Gittyup pull request #30
Opened 2021-11-23 11:04 UTC by exactly-one-kas

Allows opening repositories via Explorer context menu as new tabs

2021-11-23 11:05 UTC, exactly-one-kas commented
Implements gitahead/gitahead#218

2021-11-23 12:27 UTC, Murmele commented
Good idea!

2021-11-26 08:41 UTC, Murmele commented
@exactly-one-kas

2021-11-26 09:05 UTC, exactly-one-kas commented
I'll get to it, fixing the tests takes a lot of time, since I have no prior experience with CTest and little experience with QT

2021-11-26 10:09 UTC, Murmele commented
ok sorry

2021-12-05 17:48 UTC, Murmele commented
@exactly-one-kas can you fix the merge request, then I can merge it

2021-12-11 11:40 UTC, exactly-one-kas commented on src/app/Application.cpp
> +#define COPYDATA_WINDOW_TITLE "GitAhead WM_COPYDATA receiver 16b8b3f6-6446-4fa7-8c72-53c25b1f206c"
The window title needs to be unique so that another app doesn't send or receive IPC messages meant for Gittyup.
The GUID is just a precaution; I can remove it if you want

2021-12-21 16:49 UTC, Murmele commented
@exactly-one-kas can you resolve the GitAhead naming?

2021-12-21 17:52 UTC, Murmele requested changes

2021-12-21 17:52 UTC, Murmele commented on src/app/Application.h
> +class DBusGittyup public QObject
```suggestion
class DBusGittyup: public QObject
```

2021-12-21 17:55 UTC, exactly-one-kas commented on src/app/Application.h
> +class DBusGittyup public QObject
Okay, I'll better do a full clean rebuild, this is getting embarassing

2021-12-22 08:34 UTC, Murmele commented
> 

In which file browser did you test this?

2021-12-22 08:37 UTC, Murmele commented
On Manjaro it did not work for me. Tried with dolpin. Open with and then selected Gittyup. Do you think it might be a flatpak problem?

2021-12-22 08:58 UTC, exactly-one-kas commented
![2021-12-22 09-51-31](https://user-images.githubusercontent.com/16035731/147064500-e1ea3595-7923-433e-b2b9-9321d126a97d.png)
Double commander works fine without flatpak, I'll see if it stops working when using flatpak

2021-12-22 11:15 UTC, exactly-one-kas commented
This works fine on my machine, did you remember to activate single instance mode in the settings?

2022-01-03 15:28 UTC, Murmele commented
> 

Works fine thank you!

2022-01-03 15:29 UTC, Murmele approved these changes

2022-01-03 15:29 UTC, merged