Speedup refreshing
Murmele/Gittyup pull request #306
Opened 2022-10-12 14:58 UTC by Murmele

delete line 1-3 from the drawio image. So less DoubleTreeWidgetd::setDiff() are called which speeds up everything

fixes #141

2022-12-16 19:13 UTC, Murmele commented
Not yet working:
merge without conflicts does not jump to the newly created commit

2023-01-02 17:28 UTC, Murmele commented
> Not yet working:
> 
>     * [x]  merge without conflicts does not jump to the newly created commit
> 
>     * [ ]  When workdir is changed (New file added) Gittyup does not refresh correctly
> 
>     * [ ]  Also when removing untracked files (probably same as above)

@exactly-one-kas do you see also the second case. On Linux it refreshes as normal

2023-02-07 17:22 UTC, Murmele commented
Validation script:

```python
import os
import re
import datetime

def parse(filename: str, master: bool) -> []:

    projects = []

    print(f"Parse: {filename}")
    if not os.path.isfile(filename):
        raise Exception(f"File not found: {filename}")

    pattern_Datetime = "QDateTime\((?P<time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]*) CET Qt::LocalTime\)"
    if master:
        arg = ""
    else:
        arg = "bool"

    pattern_openProject = 'static MainWindow\s*\*\s*MainWindow::open\(const QString\s*&\s*, bool\) ": " Open project:  "(?P<project_path>.*)"'
    pattern_Repoview_refresh = f'void RepoView::refresh\({arg}\) ": " time:  {pattern_Datetime}  Set diff counter:  (?P<counter>[0-9]*)'
    pattern_DoubleTreeWidget = f'virtual void DoubleTreeWidget::setDiff\(const git::Diff\s*&\s*, const QString\s*&\s*, const QString\s*&\s*\) ": " time:  {pattern_Datetime} Counter:  (?P<counter>[0-9]*)'
    pattern_DoubleTreeWidget_finished = f'virtual void DoubleTreeWidget::setDiff\(const git::Diff\s*&, const QString\s*&, const QString\s*&\s*\) ": " finished, time:  {pattern_Datetime} Counter:  (?P<counter>[0-9]*)'
    pattern_CommitListMousePress = f'virtual void CommitList::mousePressEvent\(QMouseEvent\s*\*\s*\) ": " time:  {pattern_Datetime}'
    pattern_Repoview_refresh = re.compile(pattern_Repoview_refresh)
    pattern_DoubleTreeWidget = re.compile(pattern_DoubleTreeWidget)
    pattern_CommitListMousePress = re.compile(pattern_CommitListMousePress)
    pattern_openProject = re.compile(pattern_openProject)
    pattern_DoubleTreeWidget_finished = re.compile(pattern_DoubleTreeWidget_finished)

    repoview_refresh_time = None
    refresh_initial_setDiffCounter = 0

    datetimeformat = "%Y-%m-%d %H:%M:%S.%f"

    matchCounter = 0
    with open(filename, "r") as f:
        lines = f.readlines()

        line_number = 0
        for line in lines:
            line_number += 1
            match = re.match(pattern_openProject, line)
            if match is not None:
                project_path = match["project_path"]
                projects.append({
                    "path": project_path,
                    "refreshes": [],
                })

            match = re.match(pattern_Repoview_refresh, line)
            if match is not None:
                #print("Refresh triggered")
                repoview_refresh_time = datetime.datetime.strptime(match["time"], datetimeformat)
                refresh_initial_setDiffCounter = int(match["counter"])
                t = {
                    "refresh_time": repoview_refresh_time,
                    "refresh_initial_setDiffCounter": refresh_initial_setDiffCounter,
                    "setdiffs": [],
                    "type": "repoview_refresh"
                }
                projects[-1]["refreshes"].append(t)
                continue


            match = re.match(pattern_CommitListMousePress, line)
            if match is not None:
                repoview_refresh_time = datetime.datetime.strptime(match["time"], datetimeformat)
                refresh_initial_setDiffCounter = 0
                t = {
                    "refresh_time": repoview_refresh_time,
                    "refresh_initial_setDiffCounter": refresh_initial_setDiffCounter,
                    "setdiffs": [],
                    "type": "commitlist_selection_changed"
                }
                projects[-1]["refreshes"].append(t)
                continue

            match = re.match(pattern_DoubleTreeWidget, line)
            if match is not None:
                time = datetime.datetime.strptime(match["time"], datetimeformat)
                counter = int(match["counter"])
                matchCounter += 1

                #print(f"Counter: {matchCounter}, Difference Time: {(time - repoview_refresh_time).total_seconds()*1000}ms. Count diff: {counter - refresh_initial_setDiffCounter}")

                assert(len(projects[-1]["refreshes"]) > 0)

                t = {
                    "totalCount": matchCounter,
                    "time_start": time,
                    "timediff_ms": (time - repoview_refresh_time).total_seconds()*1000,
                    "relativeCount": counter - refresh_initial_setDiffCounter,
                    "duration_setDiff": -1
                }
                projects[-1]["refreshes"][-1]["setdiffs"].append(t)
                continue

            match = re.match(pattern_DoubleTreeWidget_finished, line)
            if match is not None:
                time = datetime.datetime.strptime(match["time"], datetimeformat)
                counter = int(match["counter"])

                # print(f"Counter: {matchCounter}, Difference Time: {(time - repoview_refresh_time).total_seconds()*1000}ms. Count diff: {counter - refresh_initial_setDiffCounter}")

                assert (len(projects[-1]["refreshes"]) > 0)

                projects[-1]["refreshes"][-1]["setdiffs"][-1]["duration_setDiff"] = (time - projects[-1]["refreshes"][-1]["setdiffs"][-1]["time_start"]).total_seconds()*1000
                continue
    return projects

def hline() -> str:
    return "-----------------------------------\n"

def diffRow(diff: dict) -> str:
    return f'c:{diff["relativeCount"]}, t:{diff["timediff_ms"]}ms, d_setDiff:{diff["duration_setDiff"]}ms'

def rowString(columns: []):
    row = "|"
    for column in columns:
        row += f"{column:40}|"
    return row

def row(header: [], diffs: []) -> str:
    r = ""
    assert(len(header) == len(diffs))

    max_len = -1
    for d in diffs:
        length = len(d["setdiffs"])
        if length > max_len:
            max_len = length
    assert(max_len > 0)

    r += rowString(header) + "\n"
    for i in range(max_len - 1):
        row_contents = []
        for diff in diffs:
            row_content = ""
            if i < len(diff["setdiffs"]) - 1:
                row_content = diffRow(diff["setdiffs"][i])
            row_contents.append(row_content)

        r += rowString(row_contents) + "\n"

    row_contents = []
    for diff in diffs:
        row_content = diffRow(diff["setdiffs"][-1])
        row_contents.append(row_content)
    r += rowString(row_contents) + "\n"
    return r

def printTable(runs):
    """
    Create caller table
    :param runs:
    :return:
    """
    table = ""
    ref_logs = runs[0]["logs"]
    for p_index in range(len(ref_logs)):
        table += hline()
        table += hline()
        project_name = ref_logs[p_index]["path"]
        table += f"Open Project: {project_name}\n"

        for refreshes_index in range(len(ref_logs[p_index]["refreshes"])):
            table += hline()
            table += f"Refresh triggered: {ref_logs[p_index]['refreshes'][refreshes_index]['type']}\n"
            names = []
            values = []
            for run in runs:
                names.append(run["name"])
                values.append(run["logs"][p_index]["refreshes"][refreshes_index])
            table += row(names, values)
            table += hline()

    print(table)

if __name__ == "__main__":
    runs = [
        {
            "name": "OptimizedRefresh",
            "logs": parse("GittyupSpeedupRefresh.txt", False)
        },
        {
            "name": "Master",
            "logs": parse("GittyupMasterRefreshOutput.txt", True)
        }
    ]

    # check that all have the same number of open project
    num_proj = len(runs[0]["logs"])
    for run in runs:
        assert len(run["logs"]) == num_proj

    # print table for optimized refresh
    print(f"Run {runs[0]['name']}")
    printTable([runs[0]])

    # print table of current master
    print(f"Run {runs[1]['name']}")
    printTable([runs[1]])
```

2023-02-13 08:45 UTC, exactly-one-kas requested changes

2023-02-13 08:45 UTC, exactly-one-kas commented on src/ui/CommitList.h
> +  bool isSuppressResetWalker();
`isResetWalkerSuppressed` would be a better name

2023-02-13 08:45 UTC, exactly-one-kas commented on src/util/Debug.h
> +#define DEBUG_REFRESH 1
Wouldn't it be better to define these as parameters via CMAKE?

2023-02-13 08:45 UTC, exactly-one-kas commented on src/util/Debug.h
> +#define DEBUG_REFRESH 1
Also: CMAKE defines `NDEBUG` for release builds, we could use that instead

2023-02-13 08:45 UTC, exactly-one-kas commented on test/rebase.cpp
> +  //  INIT_REPO("rebaseConflicts.zip", true);
Why is this all disabled?

2023-02-13 08:45 UTC, exactly-one-kas commented on test/rebase.cpp
> +  //  INIT_REPO("rebaseConflicts.zip", true);
This too

2023-02-15 18:21 UTC, Murmele commented on src/ui/CommitList.h
> +  bool isSuppressResetWalker();
fixed in 8bdfca3f37c57a05356f9e1523d97ae80f16dc8f

2023-02-15 18:30 UTC, Murmele commented on src/util/Debug.h
> +#define DEBUG_REFRESH 1
first comment changed in ba02026813dca9709ff1482e12a7ab38e09d0e4e

2023-02-15 18:33 UTC, Murmele commented on test/rebase.cpp
> +  //  INIT_REPO("rebaseConflicts.zip", true);
Hmm I don't know. I enabled them again in 59846affcd58996b9061c13ebc8c9205614bc5cf. Thanks!

2023-02-15 18:33 UTC, Murmele commented on test/rebase.cpp
> +  //  INIT_REPO("rebaseConflicts.zip", true);
Hmm I don't know. I enabled them again in 59846affcd58996b9061c13ebc8c9205614bc5cf. Thanks!

2023-02-17 11:36 UTC, Murmele commented on src/util/Debug.h
> +#define DEBUG_REFRESH 1
Now in release mode no debug messages will be send out

2023-02-25 17:23 UTC, merged