Add Gitea Support
Murmele/Gittyup pull request #313
Opened 2022-10-15 23:33 UTC by OdinVex

This is a rough, initial attempt at adding Gitea support. Some features have been tested similarly to GitHub.

Signed-off-by: Odin Vex <44311901+OdinVex@users.noreply.github.com>

2022-10-15 23:34 UTC, OdinVex commented
I tested this as far as adding a remote account and cloning a repository. History is apparently working, but my repositories are rather large, and I did not have enough time to test out pushing or pull-requesting.

2022-10-16 10:49 UTC, exactly-one-kas requested changes

2022-10-16 10:49 UTC, exactly-one-kas commented on src/host/Gitea.cpp
> +// Author: Jason Haslam
Please insert your name here (user name is also sufficient)

2022-10-16 10:49 UTC, exactly-one-kas commented on src/host/Gitea.h
> +// Author: Jason Haslam
same here

2022-10-16 10:49 UTC, exactly-one-kas commented on src/host/Gitea.cpp
> +  return QStringLiteral("https://try.gitea.io");
[try.gitea.io](https://try.gitea.io) is just an evaluation instance, [Codeberg](https://codeberg.org) is the "production" instance endorsed by the Gitea team

2022-10-16 10:50 UTC, exactly-one-kas commented
Pull requests won't work, but the account system needs an overhaul anyway, so that's fine

2022-10-16 14:33 UTC, OdinVex commented on src/host/Gitea.cpp
> +  return QStringLiteral("https://try.gitea.io");
It is evaluation, but it also has actual lifetime. Without having received any special permissions to assume a production instance, I figured the demo for this initial PR would be alright.

2022-10-16 14:35 UTC, OdinVex commented on src/host/Gitea.h
> +// Author: Jason Haslam
Same from above.

2022-10-16 14:52 UTC, OdinVex commented
I've formatted the unhappy cpp, I'll push it to my repo when I figure out this licensing bit.

2022-10-16 15:09 UTC, exactly-one-kas commented on src/host/Gitea.cpp
> +  return QStringLiteral("https://try.gitea.io");
[gitea.com](https://gitea.com/) points to Codeberg:

> If you're looking for a hosted Gitea service, [codeberg.org](https://codeberg.org/) might be what you are looking for.

But yeah, try.gitea.io will do better, since gitea.com isn't really mentioned in the docs

2022-10-16 15:09 UTC, exactly-one-kas approved these changes

2022-10-16 15:10 UTC, OdinVex commented
Reminder, the Gitea support was added by cloning the GitHub backend and simply adapting the code to Gitea with string and name changes. Some code may be left that may not have anything to do with Gitea, such as the OAuth code and the tokens. **For now, this backend only supports Basic Authentication (over HTTPS).** It can be amended later to support the Gitea API such as 2FA if someone else has the time to break it down.

2022-10-16 15:15 UTC, OdinVex commented
Regarding the clang-format of `./src/host/CMakelists.txt`, it results in a drastically different layout of the file, you might want to decide on that.

2022-10-16 15:15 UTC, exactly-one-kas commented
People with 2FA-enabled accounts can create an application token and use that as the password

This preliminary support is good enough since the only operation remote accounts provide aside from cloning is the PR button (which is only shown when the undocumented, unused environment variable `GITTYUP_OAUTH` is not empty)

2022-10-16 15:18 UTC, OdinVex commented
Regarding `gitea.com`, the front-page has this to say regarding `gitea.com`, `try.gitea.io`, and Codeberg:

    While we have open sign-ups, this server is not an equivalent to gitlab.com or github.com.
    If you're looking for a hosted Gitea service, codeberg.org might be what you are looking for.
    If you want to evaluate the Gitea software for selfhosting, create an account on try.gitea.io.

Codeberg isn't endorsed, merely suggested. I think `try.gitea.io` being 'evaluation' is perfect for a default URL for Gitea Remotes.

2022-10-16 15:22 UTC, OdinVex commented
I also did not bump version, that's something the project lead(ers) should handle. This is non-breaking and simply additional, so maybe a patch version.

2022-10-16 15:36 UTC, exactly-one-kas commented
> Regarding the clang-format of `./src/host/CMakelists.txt`, it results in a drastically different layout of the file, you might want to decide on that.

Huh, it's also failing the CI check? We use cmake-format with the default settings, do you have some custom rules set up?
Anyway, I'll just fix the formatting for you

2022-10-16 15:37 UTC, exactly-one-kas commented
> I also did not bump version, that's something the project lead(ers) should handle. This is non-breaking and simply additional, so maybe a patch version.

You did everything right, version bumps only happen for hotfixes and releases, new features usually don't land a new version on their own

2022-10-16 15:41 UTC, OdinVex commented
> > Regarding the clang-format of `./src/host/CMakelists.txt`, it results in a drastically different layout of the file, you might want to decide on that.
> 
> Huh, it's also failing the CI check? We use cmake-format with the default settings, do you have some custom rules set up? Anyway, I'll just fix the formatting for you

I cloned the repo and literally used a text editor while copy-pasting. Manually running clang-format (llvm style) myself results in it wanting to format files that are in Murmele/Gittyup even.

2022-10-16 16:00 UTC, OdinVex commented
Fixes #64.

2022-10-16 16:07 UTC, exactly-one-kas commented
> I've been using clang-format -style=llvm ./FILES.

Ah, that explains it; we have a `.clang-format` file in the repository root, you can just run `clang-format` without the style argument and it should pick our file right up

2022-10-16 16:07 UTC, merged

2022-10-16 16:24 UTC, OdinVex commented
Is there an ETA milestone for this to be rolled out, or will it be added to #272? Seems a good time to add it to streamline.

2022-10-16 16:27 UTC, exactly-one-kas commented
It's due to be released with [1.2.0](https://github.com/Murmele/Gittyup/milestone/1)

We hope to release as soon as #312 is done