Publish persistent version on GitHub CI
Murmele/Gittyup pull request #328
Opened 2022-10-22 22:18 UTC by exactly-one-kas

I saw this commit lying around for the 1.1.2 version and I thought we might want this all the time lol

2022-10-23 13:37 UTC, Murmele commented
Good point. In that case we have one stable release plus one with the version number.

2022-10-23 13:39 UTC, Murmele commented on .github/workflows/build.yml
> +      - name: Update GitHub release (stable / latest tag)
```suggestion
      - name: Update GitHub release (latest tag)
        if: ${{ env.IS_RELEASE == 'false'}}
```
What do you think about this?

2022-10-24 04:47 UTC, exactly-one-kas commented on .github/workflows/build.yml
> +      - name: Update GitHub release (stable / latest tag)
Yep, that should work

2022-10-24 08:27 UTC, Murmele commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.VERSION }}
```suggestion
```

This will not work, because IS_RELEASE is only true if a new release tag will be set.

2022-10-24 09:00 UTC, exactly-one-kas commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.VERSION }}
What do you mean? That release action is specifically for new tagged releases?

2022-10-24 09:38 UTC, Murmele commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.VERSION }}
but this will create a new release tag, which was already set manually or am I wrong?

Currently the workflow is:
- merge release mr
- tag commit with release version
- CI: create new stable release

2022-10-24 09:53 UTC, Murmele commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.VERSION }}
I take everything back. I thought this creates a new version tag in git. Sorry

2022-10-24 09:56 UTC, Murmele commented
In that case we don't have any stable tag anymore or? That means we have to update the versions on the webpage to point to the new version?

2022-10-24 10:32 UTC, exactly-one-kas commented
That's why I initally kept the stable tag lol

Should I just put it back?

2022-10-24 10:33 UTC, exactly-one-kas commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.VERSION }}
No, you're right, it also creates a GIT tag (I didn't know that)

How about the following: We remove all old GitAhead version tags and switch to using unprefixed `v#.#.#` tags? That way we get "clean" GIT tags and release labels

2022-10-24 11:32 UTC, Murmele commented
> 

Haha ys I think we have to do it ^^. Not that elegant to have a stable, latest and a version release but there is no other way or?

2022-10-24 13:39 UTC, exactly-one-kas commented
Take a  look at this: https://github.com/exactly-one-kas/Gittyup/releases/tag/v13.37.69

2022-10-24 13:43 UTC, alerque commented
> That means we have to update the versions on the webpage to point to the new version?

I'd say get rid of the "stable" tag altogether.

GitHub supports a *keyword* (not a tag) called "latest" that will always be a fresh link to the latest tagged release marked as stable in their API. Note that the URL for this is not quite the same as for a tag, two segments of the path are reversed. This is far superior to having a confusing mess of sliding tags like "stable".

2022-10-24 14:06 UTC, Murmele commented
> 

Currently latest is pointing to the latest commit on master, but this is not indended to be a stable version

2022-10-24 14:07 UTC, Murmele requested changes

2022-10-24 14:09 UTC, Murmele requested changes

2022-10-24 14:09 UTC, Murmele commented on .github/workflows/build.yml
> +            **/artifacts/Gittyup mac/Gittyup*.dmg
why using mac here?

2022-10-24 14:15 UTC, Murmele commented on .github/workflows/build.yml
> +          automatic_release_tag: ${{ steps.version.outputs.VERSION }}
I would prefer doing that for the next release, we have to check where we have to change the version numbering (Source code, github workflow, ...).

2022-10-24 15:13 UTC, alerque commented
> Currently latest is pointing to the latest commit on master, but this is not indended to be a stable version

That's why I specified that there is a latest *keyword* **not a tag**.

This is the link to your tag (which I think should also be dropped, see below):

https://github.com/Murmele/Gittyup/releases/tag/latest

This is the keyword link:

https://github.com/Murmele/Gittyup/releases/latest

This will update automatically to whatever the most recent *release* (not just tag, but GitHub Release not marked as pre-release).

As such this keyword can be used to completely replace what you are currently doing redundantly with the "stable" tag.

----

The "stable" system can definitely go with no loss of function. However secondarily the "latest" tag doesn't really serve a purpose that isn't accomplished other ways already. If you want to expose CI artifacts for HEAD you can just like to the actions on the branch.

2022-10-24 19:57 UTC, Murmele commented
> > Currently latest is pointing to the latest commit on master, but this is not indended to be a stable version
> 
> That's why I specified that there is a latest _keyword_ **not a tag**.
> 
> This is the link to your "stable" tag (and also "latest" tag which I think should also be dropped, see below):
> 
> [`https://github.com/Murmele/Gittyup/releases/tag/stable`](https://github.com/Murmele/Gittyup/releases/tag/stable) [`https://github.com/Murmele/Gittyup/releases/tag/latest`](https://github.com/Murmele/Gittyup/releases/tag/latest)
> 
> This is the keyword link:
> 
> [`https://github.com/Murmele/Gittyup/releases/latest`](https://github.com/Murmele/Gittyup/releases/latest)
> 
> This will update automatically to whatever the most recent _release_ (not just tag, but GitHub Release not marked as pre-release).
> 
> As such this keyword can be used to completely replace what you are currently doing redundantly with the "stable" tag.
> 
> The "stable" system can definitely go with no loss of function. However secondarily the "latest" tag doesn't really serve a purpose that isn't accomplished other ways already. If you want to expose CI artifacts for HEAD you can just like to the actions on the branch.

But is it then also possible to get a link to the latest release, prerelease and stable?

2022-10-25 14:41 UTC, Murmele commented
@alerque @exactly-one-kas what do you think about my solution?

In that case the latest tag will always set and if we have a release we additionally creating a stable release?

2022-10-25 20:03 UTC, exactly-one-kas commented
Good idea

2022-10-26 06:29 UTC, Murmele approved these changes

2022-10-28 05:22 UTC, exactly-one-kas commented
@Murmele I pushed a change to clarify what the releases names mean. If you're okay with that, you can merge

2022-10-28 05:59 UTC, Murmele commented
> @Murmele I pushed a change to clarify what the releases names mean. If you're okay with that, you can merge

great thanks!

2022-10-28 05:59 UTC, merged