fix download URL
Murmele/Gittyup pull request #344
Opened 2022-10-31 14:02 UTC by Murmele

fixes #335

2022-10-31 14:11 UTC, alerque requested changes

2022-10-31 14:11 UTC, alerque commented on src/update/Updater.cpp
> +                         "latest/Gittyup%1%2.%3";
I don't think this is right, to use the GitHub release keywords the scheme needs to be `releases/latest/download` not `releases/download/latest`. Also this scheme should probably be used just to download the manifest, then the manifest used to extract the tag name and construct the actual download URL.

2022-10-31 14:24 UTC, Murmele commented on src/update/Updater.cpp
> +                         "latest/Gittyup%1%2.%3";
https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release

2022-10-31 20:07 UTC, alerque commented on src/update/Updater.cpp
> +                         "latest/Gittyup%1%2.%3";
The one I recommend (and the GH docs you link to recommends) is the **keyword** "latest" that automatically gets URL redirected to the actual tag that happens to be the most recent stable release. The one you used is a **tag** that you have to manually create and update and isn't actually the version tag but a separate one presumably on the same commit but a parallel universe to the actual versioned tags. You want to stop having to create sliding tags for things and only use tags with actual version numbers and use the GH release API to link to the current latest release, not a tag that just happens to have the name "latest".

2022-11-09 10:13 UTC, Murmele commented
@exactly-one-kas  @alerque should we create a bug fix release after this MR

We still need a sliding tag, because the latest push to master cannot be retrieved from the github API.

2022-11-09 10:13 UTC, Murmele commented on docs/changelog.md
> +
```suggestion
* Fix Segmentation fault when ignoring files
```

2022-11-09 10:14 UTC, Murmele commented on docs/changelog.md
> +### v1.2.1 - 2022-10-31
```suggestion
### v1.2.1 - 2022-11-09
```

2022-11-09 10:23 UTC, alerque commented
> @exactly-one-kas @alerque should we create a bug fix release after this MR

Yes, pending the additional fix suggested below.

> We still need a sliding tag, because the latest push to master cannot be retrieved from the github API.


Actually you can, but what you are doing right now is regularly attaching binary artifacts to the HEAD commit, and that is a bit more complicated.

You can keep a sliding tag if you really don't want to change the architecture, **but the tag should not  be named "latest" it should be "snapshot" or "development" or something like that**. I suggest fixing the code now to in the future look for a tag with the proper name for unstable snapshot builds so that there isn't future confusion between the "latest" keyword GitHub uses and a manual tag of the same name.

2022-11-10 07:32 UTC, Murmele commented
for me **development** sounds fine. @exactly-one-kas do you agree with it?

2022-11-10 08:26 UTC, exactly-one-kas commented
`development` is fine by me

2022-11-10 08:33 UTC, Murmele commented on docs/changelog.md
> +### v1.2.1 - 2022-11-09
```suggestion
### v1.2.1 - 2022-11-10
```

2022-11-10 08:34 UTC, Murmele commented
After merging we can cross check the urls again and if they are working I will set the tag. Then we have to create last time the stable release tag

2022-11-10 09:58 UTC, alerque approved these changes

2022-11-10 09:58 UTC, alerque approved these changes
Looks right to me now.

2022-11-15 06:56 UTC, exactly-one-kas approved these changes

2022-11-17 15:27 UTC, merged