Credential store
Murmele/Gittyup pull request #347
Opened 2022-11-01 09:42 UTC by H-4ND-H

Revise the mechanism with which Gittyup instantiates credential store for retrieving and storing credentials.(#290)

User can now choose which store to use in general setting, and this setting will apply to git global config file.

2022-11-09 10:57 UTC, exactly-one-kas requested changes
This looks good so far, just a few changes and you're good to go

2022-11-09 10:57 UTC, exactly-one-kas commented on src/cred/CredentialHelper.cpp
> +const QString winCredStoreName = "winCred";
This should be all lowercase to match GIT's `credential-wincred`

2022-11-09 10:57 UTC, exactly-one-kas commented on src/dialogs/SettingsDialog.cpp
> +      Settings::instance()->setValue(
I think this should be removed, saving this in two places doesn't really make sense
All other places that use this setting should be changed to use GIT's `credential.helper`

2022-11-09 10:57 UTC, exactly-one-kas commented on src/dialogs/SettingsDialog.cpp
> +    mAvailableStores = new QComboBox(this);
This should have `editable = true`, so that custom credential helpers are recognized and can be entered

2022-11-14 15:11 UTC, H-4ND-H commented on src/dialogs/SettingsDialog.cpp
> +    mAvailableStores = new QComboBox(this);
Shall we validate the name entered or fall back to manual credential dialog if name is wrong or lib does not exist?

2022-11-14 15:11 UTC, H-4ND-H commented on src/dialogs/SettingsDialog.cpp
> +      Settings::instance()->setValue(
true, I will fix this

2022-11-15 07:06 UTC, exactly-one-kas commented on src/dialogs/SettingsDialog.cpp
> +    mAvailableStores = new QComboBox(this);
I think a warning message would make sense. Allowing users to input "wrong" values should be an option, especially if they're testing new credhelpers

An additional fallback to a credential dialog makes sense even if the setting is correct an we don't get any credentials. Otherwise the user couldn't add any new credentials via Gittyup

2022-11-15 07:07 UTC, exactly-one-kas commented on src/cred/CredentialHelper.cpp
> +const QString winCredStoreName = "winCred";
Yes, even with our special `wincred` case, this makes it more clear that we're using the same underlying mechanism

2022-11-15 07:11 UTC, exactly-one-kas commented on src/cred/CredentialHelper.cpp
> +  list.append(winCredStoreName),
This needs a semicolon instead of the comma

2022-11-30 11:51 UTC, H-4ND-H commented on src/dialogs/SettingsDialog.cpp
> +    mAvailableStores = new QComboBox(this);
Pls check the fix provided

2023-01-11 09:02 UTC, CharliesAngel1 approved these changes

2023-01-22 07:31 UTC, exactly-one-kas approved these changes

2023-01-26 13:11 UTC, H-4ND-H commented
@exactly-one-kas I think its ready for merge, pls have a look

2023-01-30 08:15 UTC, merged

2023-01-30 08:15 UTC, exactly-one-kas commented
Thank you for your work!

2023-02-16 12:28 UTC, Murmele commented
@H-4ND-H sorry for asking now. Previously on windows wincred was the default store type.
![grafik](https://user-images.githubusercontent.com/10099533/219364801-e1faaf61-38ab-4568-9cf5-2bf5a2376843.png)

Would it make sense to make it also in the new approach the default?

2023-02-21 09:49 UTC, H-4ND-H commented
@Murmele, sry for the delay,  The new approach looks at global git config, so to your question, if no store is set in global config we can auto choose `wincred` in case of `windows`. but the fact that you have to enter password each and every time, it more looks like there is a problem in saving global config in windows, in linux I tested and it works as intended.

2023-02-21 16:59 UTC, Murmele commented
@H-4ND-H don't worry. @exactly-one-kas fixed an issue in 5afe9d1c699dffd18f691152105ec2626e0e9616 

With `cache` I have to enter the password every time I am opening Gittyup or am I wrong? (This is what happens for me)

2023-02-21 17:03 UTC, H-4ND-H commented
> @H-4ND-H don't worry. @exactly-one-kas fixed an issue in 5afe9d1c699dffd18f691152105ec2626e0e9616 
> 
> With `cache` I have to enter the password every time I am opening Gittyup or am I wrong? (This is what happens for me)

Sure, cache stores data on a map with class storage life time, so that's the true behavior, I thought u see the same thing with wincred

2023-02-21 21:34 UTC, Murmele commented
No wincred is persistent. There it is fine