migrated to qt6
Murmele/Gittyup pull request #429
Opened 2023-01-17 15:31 UTC by wolfseifert

I have just migrated a fork of Gittyup to Qt6.

It compiles (without deprecation warnings) and seems to run, but is still mostly untested (on Manjaro-KDE-Linux only).

2023-01-17 15:49 UTC, Murmele commented on src/dialogs/CMakeLists.txt
> +find_package(Qt6 COMPONENTS Core5Compat REQUIRED)
Do we need this?

2023-01-17 15:49 UTC, Murmele commented on CMakeLists.txt
> +    Qt6
we have to find a way to support both

2023-01-17 18:09 UTC, alerque commented on CMakeLists.txt
> +    Qt6
Do we? What platforms/targets don't have Qt6 on the menu already and/or won't soon? It seems to be a project like this would benefit from staying on top of the toolkit/library game and any effort back-porting to older versions should be on an as-demanded basis and provided by the people that really want to see it happen for whatever reason. The main development effort should be on the latest stable releases when possible and this seems like a great opportunity to hit that target.

2023-01-17 18:12 UTC, wolfseifert commented on src/dialogs/CMakeLists.txt
> +find_package(Qt6 COMPONENTS Core5Compat REQUIRED)
No, Core5Compat is obsolete.

2023-01-17 18:17 UTC, wolfseifert commented on CMakeLists.txt
> +    Qt6
Supporting both would mean lots of #ifdefs, a nightmare...

2023-10-08 07:56 UTC, Murmele requested changes

2023-10-08 07:56 UTC, Murmele commented on src/app/Gittyup.cpp
>    Application app(argc, argv, true);
Why is this anymore required?

2023-10-08 07:56 UTC, Murmele commented on src/dialogs/ConfigDialog.cpp
> -    watcher->setFuture(QtConcurrent::run(repo, &git::Repository::lfsTracked));
I understand why you changed it, but I don't understand why it worked also the other way?

2023-10-08 07:56 UTC, Murmele commented on src/dialogs/DeleteBranchDialog.cpp
> +      git::Result (git::Remote::*push)(git::Remote::Callbacks*, const QStringList&) = &git::Remote::push;
what is the benefit of this function pointer?

2023-10-08 08:25 UTC, Murmele commented on CMakeLists.txt
> +    Qt6
I rebased the branch, maybe we can go just with Qt6

2023-10-08 08:49 UTC, Murmele commented
@exactly-one-kas do you think we still need win32?

2023-10-08 09:19 UTC, Murmele commented
@exactly-one-kas Can you test and build this branch on Arch Linux?

2023-10-08 09:20 UTC, Murmele commented on src/dialogs/CMakeLists.txt
> +find_package(Qt6 COMPONENTS Core5Compat REQUIRED)
I removed it

2023-10-08 09:21 UTC, Murmele commented on CMakeLists.txt
> +    Qt6
@exactly-one-kas do you have anything against it?

2023-10-08 11:17 UTC, Murmele commented on src/dialogs/ConfigDialog.cpp
> -    watcher->setFuture(QtConcurrent::run(repo, &git::Repository::lfsTracked));
Ok it does not compile the other way around, but the function definition looks same in Qt5 and Qt6

2023-10-27 16:17 UTC, Murmele commented
Mac: change CustomTheme_mac.mm use float

Win:  D:/a/Gittyup/Gittyup/src/index/indexer.cpp:61:3: error: no matching function for call to 'CreateDirectoryW'
  CreateDirectory(dir, NULL);

2023-11-07 22:30 UTC, LenaWil commented
> Is there anybody which can fix the build error in my Qt6 branch? #429

Is there still stuff that needs testing?

2023-11-08 13:08 UTC, Murmele commented
> > Is there anybody which can fix the build error in my Qt6 branch? #429
> 
> Is there still stuff that needs testing (on Mac)?

Yes can you test if it is working? On windows the theme looks wrong this is another point.

Needs to be tested
- [ ] MacOs
Needs to be fixed:
- [ ] Windows theme looks wrong

2023-11-15 14:38 UTC, LenaWil commented
I get the following error when opening Gittyup build https://github.com/Murmele/Gittyup/actions/runs/6725527056:

```
dyld[86107]: Library not loaded: @rpath/QtConcurrent.framework/Versions/A/QtConcurrent
  Referenced from: <B62A89B5-9AEE-3037-8535-B06DF4911B33> /Volumes/Gittyup/gittyup.app/Contents/MacOS/gittyup
  Reason: tried: '/usr/local/qt/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/qt/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/Volumes/Gittyup/gittyup.app/Contents/MacOS/../Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/usr/local/qt/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/qt/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/Volumes/Gittyup/gittyup.app/Contents/MacOS/../Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/Library/Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/System/Library/Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file, not in dyld cache)
[1]    86107 abort      /Volumes/Gittyup/gittyup.app/Contents/MacOS/gittyup
```

2023-11-17 07:49 UTC, Murmele commented
> I get the following error when opening Gittyup build https://github.com/Murmele/Gittyup/actions/runs/6725527056 on macOS 14.1 (Rosetta2):
> 
> ```
> dyld[86107]: Library not loaded: @rpath/QtConcurrent.framework/Versions/A/QtConcurrent
>   Referenced from: <B62A89B5-9AEE-3037-8535-B06DF4911B33> /Volumes/Gittyup/gittyup.app/Contents/MacOS/gittyup
>   Reason: tried: '/usr/local/qt/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/qt/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/Volumes/Gittyup/gittyup.app/Contents/MacOS/../Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/usr/local/qt/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/qt/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/Volumes/Gittyup/gittyup.app/Contents/MacOS/../Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/Library/Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file), '/System/Library/Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent' (no such file, not in dyld cache)
> [1]    86107 abort      /Volumes/Gittyup/gittyup.app/Contents/MacOS/gittyup
> ```

Thanks for the feedback. I have to set up a virtual machine to check it out.

2023-12-13 21:17 UTC, 0verEngineer commented
@wolfseifert Can you give me rights to push?

2023-12-15 06:30 UTC, wolfseifert commented
I added Julian Hackinger as collaborator.

2023-12-15 09:44 UTC, 0verEngineer commented
![Screenshot 2023-12-15 at 10 42 54](https://github.com/Murmele/Gittyup/assets/105462605/b76d453a-24d7-4f93-8b14-f3627dd61627)
Is this only on MacOS?

2023-12-15 10:11 UTC, Murmele commented
Is the mr is rebased on the latest master?

2023-12-15 10:15 UTC, Murmele commented
For appimage: libxcb-cursor0 must be installed as well, otherwise the linux ci build fails

2023-12-15 11:20 UTC, 0verEngineer commented
![Screenshot 2023-12-15 at 12 10 45](https://github.com/Murmele/Gittyup/assets/105462605/197fa021-3799-417a-b2b6-361bef766e6f)
![Screenshot 2023-12-15 at 12 14 53](https://github.com/Murmele/Gittyup/assets/105462605/3d2d8b5c-0c5b-405c-919e-8e2bd4797e97)

### Theme problems on MacOS as well:
- highlighting of selected Repo only slightly visible (sshTools is highlighted)
- `Use Ours` and `Use Theirs` button not colored

### .git name problem:
- Happens only update from Gittyup 1.3.0 to the QT6 Version, newly added repos are fine.
- After rebase there is a recent repo `.git` as well, this was not the case before the rebase and this repo was not in the recent repos on Gittyup 1.3.0, it appeared without adding (It is the GittyupQT6 repo i work in atm.)

2024-01-21 11:21 UTC, Murmele commented
@probonopd maybe you have an idea why the appimage builder does not find libqxcb.

```
2024/01/21 11:17:37 Detected Qt 6
2024/01/21 11:17:37 Using $QTDIR: /home/runner/work/Gittyup/Qt/6.5.*/gcc_64
2024/01/21 11:17:37 Looking in /home/runner/work/Gittyup/Qt/6.5.*/gcc_64/plugins
2024/01/21 11:17:37 Could not find 'plugins/platforms/libqxcb.so' in qtPrfxpath, exiting
```

I printed the paths:

### Show QTDIR

bin
doc
include
lib
libexec
metatypes
mkspecs
modules
phrasebooks
plugins
qml
resources
translations
### Show QTDIR plugins

designer
egldeviceintegrations
generic
iconengines
imageformats
networkinformation
platforminputcontexts
platforms
platformthemes
printsupport
qmllint
qmltooling
sqldrivers
tls
wayland-decoration-client
wayland-graphics-integration-client
wayland-shell-integration
xcbglintegrations
### Show QTDIR plugins platforms
libqeglfs.so
libqlinuxfb.so
libqminimal.so
libqminimalegl.so
libqoffscreen.so
libqvkkhrdisplay.so
libqvnc.so
libqwayland-egl.so
libqwayland-generic.so
libqxcb.so

2024-01-21 11:24 UTC, Murmele commented
Probably I broke MacOs build with 9c349e5dc2e7ce49bce548019987c4a1b36d8f8d..7b1216860ed06926d0b9bbc9e03ed9e6ff730d6e, but first lets fix Appimage then I can revert the changes

2024-02-06 09:01 UTC, Murmele commented on .github/workflows/build.yml
> +          - version: 6.5.*
```suggestion
          - version: 6.5.3
```

2024-02-06 09:17 UTC, Murmele commented
@probonopd It seems that it was due to the wildcard in the qt version. Just for your information: https://github.com/Murmele/Gittyup/pull/429/commits/00675a77f7eef715e00c2b5bd6b603a8d9a7eb96

2024-02-26 13:24 UTC, Murmele commented
We can check the commit "c0754a0e061352c8d8d4434952115796063c9401" from GitAhead where the port happened

2024-05-22 09:56 UTC, Murmele commented on .github/workflows/build.yml
> +          - version: 6.5.3
updating? Maybe it fixes the theme issues?

2024-05-22 16:40 UTC, Murmele commented
Then we need to have a deeper look into it because GitAhead does not have this problem with Qt6

2024-06-14 13:24 UTC, 0verEngineer commented
I just tried to find the differences in GitAheads QT6 commit in order to fix our theming problems.

First things first:
# Theme problems on MacOS:
- highlighting of selected Repo only slightly visible (sshTools is highlighted)
  - This is the same as in the QT5 Gittyup
- Use Ours and Use Theirs button not colored
  - This is also the same as in the QT5 Gittyup - @Murmele We should open another issue for this as it is confusing

# Theme problems on Linux:
- I will check them and hopefully fix them later

# .git name problem:
@Murmele This has nothing to do with this QT6 migration, we already talked about this somewhere else, am i correct?

2024-06-15 07:39 UTC, Murmele commented
> I just tried to find the differences in GitAheads QT6 commit in order to fix our theming problems.
> 
> First things first:
> # Theme problems on MacOS:
> 
>     * highlighting of selected Repo only slightly visible (sshTools is highlighted)
>       
>       * This is the same as in the QT5 Gittyup
> 
>     * Use Ours and Use Theirs button not colored
>       
>       * This is also the same as in the QT5 Gittyup - @Murmele We should open another issue for this as it is confusing
> 
> 
> # Theme problems on Linux:
> 
>     * The theme problems on linux disappered
> 
> 
> # .git name problem:
> 
> @Murmele This has nothing to do with this QT6 migration, we already talked about this somewhere else, am i correct?

You mean https://github.com/Murmele/Gittyup/issues/760?

2024-06-15 11:54 UTC, 0verEngineer commented
> You mean #760?

Yes, but is there already an issue for the "Use Ours", "Use Theirs" button color problem? This happens in Gittyup 1.4.0 on MacOS for me.

2024-06-15 12:31 UTC, 0verEngineer commented
@exactly-one-kas If you have some time can you please check out the Windows theming problem this branch has, i am unable to build openssl on windows..

2024-06-17 09:47 UTC, Murmele commented
Currently in Windows it looks like this:
![grafik](https://github.com/Murmele/Gittyup/assets/10099533/a062ac7a-5288-4b98-b3b2-6d7e3d9650b9)

2025-01-28 07:50 UTC, merged