Remove tracking code
Murmele/Gittyup pull request #58
Opened 2021-12-08 13:51 UTC by stefanknotzer

Additional fixed some annoying warnings

2021-12-09 14:46 UTC, Murmele commented
do you know why the linux build fails? Seems not to be code related but something with ninja

2021-12-09 17:12 UTC, Murmele requested changes

2021-12-09 17:12 UTC, Murmele commented on src/dialogs/ConfigDialog.cpp
> +      git::Config config = mRepo.config();
why not using directly mRepo.config()?

2021-12-10 14:39 UTC, stefanknotzer commented on src/dialogs/ConfigDialog.cpp
> +      git::Config config = mRepo.config();
When using Qt Creator 6.0.0 (Windows 10):
ConfigDialog.cpp:120:7: Call to temporary is a no-op: git::Config::setValue [clazy-writing-to-temporary}
![no-op](https://user-images.githubusercontent.com/67198194/145590999-10dcd55d-f923-4e6f-898b-915562935711.png)
I wanted to get rid of these warnings...

2021-12-10 16:46 UTC, Murmele commented on src/dialogs/ConfigDialog.cpp
> +      git::Config config = mRepo.config();
ok

2021-12-10 16:46 UTC, merged

2021-12-26 12:30 UTC, KOLANICH commented on src/ui/RepoView.cpp
> +  QTextStream(&file) << name << "\n";
Probably unrelated changes like this one shoudn't have gone into this PR.

2021-12-27 11:00 UTC, stefanknotzer commented on src/ui/RepoView.cpp
> +  QTextStream(&file) << name << "\n";
That is like a very bad habit: annoying warnings need to be fixed. And also irritating whitespaces...
I am going to make another appointment with my therapist...

2021-12-27 13:06 UTC, Murmele commented on src/ui/RepoView.cpp
> +  QTextStream(&file) << name << "\n";
are there many of them? Maybe we can remove all of them in one merge request?

2021-12-27 19:52 UTC, KOLANICH commented on src/ui/RepoView.cpp
> +  QTextStream(&file) << name << "\n";
It is pointless to remove them when they have already landed into the history. I mean that when commits touch unrelared things it is hard to audit such commits.

2021-12-28 06:48 UTC, Murmele commented on src/ui/RepoView.cpp
> +  QTextStream(&file) << name << "\n";
I agree with you. So we have to be more carefully with it.

2021-12-28 13:58 UTC, stefanknotzer commented on src/ui/RepoView.cpp
> +  QTextStream(&file) << name << "\n";
I will support this policy on future pull requests.