Update README.md
Murmele/Gittyup pull request #605
Opened 2023-07-28 15:13 UTC by vthg2themax

Create a section to help for new people building this project

2023-07-29 08:23 UTC, Murmele requested changes

2023-07-29 08:23 UTC, Murmele commented on README.md
> +cd ~/Nextcloud/Projects/gittyup
```suggestion
cd <path to repository>/gittyup
```

2023-07-29 08:23 UTC, Murmele commented on README.md
> +cd ~/Nextcloud/Projects/gittyup
```suggestion
cd <path to repository>/gittyup
```

2023-07-29 08:24 UTC, Murmele commented
Hi, there is already a how to build section, why do you need an extra one?

2023-07-29 17:22 UTC, vthg2themax commented
This just makes it easy to create a build.sh file to automatically let a new user who downloads the source to quickly create a new executable on Linux. Please let me know if that's not something you want, or if it should be put somewhere else.

2023-07-29 17:22 UTC, Bian-Sh commented
收到

2023-07-29 17:25 UTC, Murmele commented
@vthg2themax Can you add a script to the pack folder and refering in the Readme to that script? So a user can directly download it and creating a package

2023-07-31 12:43 UTC, vthg2themax reviewed
Looks good to me. Let me know if you have other thoughts.

2023-07-31 17:49 UTC, Murmele requested changes

2023-07-31 17:49 UTC, Murmele commented on README.md
> +### A Convenient Shell Script for Linux is available in the following location:
```suggestion
### A Convenient Shell Script for Ubuntu is available [here](https://raw.githubusercontent.com/Murmele/Gittyup/master/pack/buildUbuntu.sh), and will install all the necessary prerequisites, and build a release version for immediate use.
```

2023-07-31 17:49 UTC, Murmele commented on README.md
> +`pack/build.sh`, and will install all the necessary prerequisites, and build a release version for immediate use.
```suggestion
```

2023-07-31 17:49 UTC, Murmele commented on README.md
> +### A Convenient Shell Script for Linux is available in the following location:
What do you think about this? Please rename build.sh to buildUbuntu.sh

2023-08-01 10:41 UTC, vthg2themax commented
@Murmele I think your edits are wonderful. Thank you! Let me know if there's anything further that should be modified.

2023-08-01 10:43 UTC, vthg2themax commented
@Murmele This link appears to not work:
https://raw.githubusercontent.com/Murmele/Gittyup/master/pack/buildUbuntu.sh
Is that something that will be created later, or do I need to rename something?

2023-08-03 04:41 UTC, Murmele commented
> @Murmele This link appears to not work: https://raw.githubusercontent.com/Murmele/Gittyup/master/pack/buildUbuntu.sh Is that something that will be created later, or do I need to rename something?

@vthg2themax the link will work as soon it is merged, but you have to rename the shell script to buildUbuntu.sh ;)

2023-08-22 13:23 UTC, vthg2themax commented
I renamed the file. Thank you for the reminder!

2023-08-22 17:00 UTC, vthg2themax reviewed
I think this should do it

2023-08-23 11:05 UTC, Murmele requested changes

2023-08-23 11:05 UTC, Murmele commented on pack/Readme.md
> +Linux (Tested On Ubuntu 22.04LTS) version is available in the build.sh file included in this directory.
```suggestion
Linux (Tested On Ubuntu 22.04LTS) version is available in the buildUbuntu.sh file included in this directory.
```

2023-08-23 11:37 UTC, Murmele approved these changes

2023-08-23 11:37 UTC, merged