Enable line wrapping
Murmele/Gittyup pull request #709
Opened 2024-03-07 07:55 UTC by jensenr30

Line wrapping can be enabled/disabled with a setting in `Tools->Options->Diff->Wrap Lines`.  This closes #706.

This addresses the second half of #514.  The second half of issue 514 was: bad user experience when scrolling down through the DiffView.  But with line wrapping enabled, the horizontal scroll bars disappear.  That prevents the mouse scroll wheel from being captured by the horizontal scroll bar.

Demo:

[wrap-lines.webm](https://github.com/Murmele/Gittyup/assets/3083835/f44666d1-76d9-4832-a78a-f89df74e0af4)

[wrap-lines-scroll.webm](https://github.com/Murmele/Gittyup/assets/3083835/967e653d-5d19-4df5-9167-24e6af63a71d)

2024-03-07 09:25 UTC, Murmele commented
Thank you very much for the change!

2024-03-07 09:53 UTC, Murmele commented on src/conf/Settings.cpp
> +  setValue(kWrapLines, wrap, true);
Hmm I am not sure if we should change the default behaviour.

2024-03-07 09:53 UTC, Murmele commented on src/editor/TextEditor.cpp
> +
Hmm I am not sure if we should change the default behaviour.

2024-03-08 02:50 UTC, jensenr30 commented on src/conf/Settings.cpp
> +  setValue(kWrapLines, wrap, true);
I think `true` refers to the third argument which is "refresh".  I think it has to do with forcing QT to update stuff, but I'm not sure.

In any case, I tested with this code as-is, and the default behavior does not wrap lines.  So this should be OK.

2024-03-08 08:29 UTC, jensenr30 commented on src/editor/TextEditor.cpp
> +
Ok.  I changed this line of code to `setWrapMode(SC_WRAP_NONE);`.  I tested this by running gittyup after `rm ~/.config/gittyup.github.com/Gittyup.conf ` and Line wrapping is disabled by default.

2024-03-08 08:31 UTC, jensenr30 commented
@Murmele 
> Can you add an entry to the changelog: https://github.com/Murmele/Gittyup/blob/master/docs/changelog.md You can add your gif also to the website when you add an entry at: https://github.com/Murmele/Gittyup/blob/master/docs/index.md.

Done!  I recorded a better video for the website:

[line-wrap-demo-2.webm](https://github.com/Murmele/Gittyup/assets/3083835/ce71236d-74b8-4f67-9e55-657ff2f184fc)

2024-03-15 16:01 UTC, Murmele commented
Thanks I hope I can have a look into it next days.

2024-03-15 16:07 UTC, Murmele requested changes

2024-03-15 16:07 UTC, Murmele commented on docs/changelog.md
> +* UI(Diff View): Added line wrapping option in Tools->Options->Diff
```suggestion
* UI(Diff View): Added line wrapping option in Tools - Options - Diff
```
I think the `>` makes problems

2024-03-16 07:04 UTC, Murmele approved these changes

2024-03-16 07:05 UTC, merged